{application,advent_of_code,
             [{optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,httpoison]},
              {description,"advent_of_code"},
              {modules,['Elixir.Application','Elixir.Inputs','Elixir.PartOne',
                        'Elixir.PartTwo']},
              {registered,[]},
              {vsn,"0.1.0"},
              {mod,{'Elixir.Application',[]}}]}.
